# Fixed docker-compose.yml
services:
    mongo:
        image: mongo:latest
        container_name: JurnlDockContainer
        # Use tmpfs for logs (faster, non-persistent)
        tmpfs:
            - /tmp:noexec,nosuid,size=1g
        volumes:
            # Option 1: Use standard Docker volumes (recommended)
            - mongo_data:/data/db
            - mongo_config:/data/configdb

            # Option 2: Use tmpfs for ultimate speed (data lost on restart)
            # tmpfs:
            #     - /data/db:noexec,nosuid,size=2g
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: jurnl
        ports:
            - '127.0.0.1:27017:27017'
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 5s
            timeout: 2s
            retries: 3
            start_period: 10s
        restart: unless-stopped
        command: [
            '--auth',
            '--bind_ip_all',
            '--wiredTigerCacheSizeGB', '1',  # Limit cache size
            '--wiredTigerEngineConfigString', 'cache_size=1GB',
            '--quiet',  # Reduce logging
        ]
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.enable_icc: "true"
            com.docker.network.driver.mtu: "1500"

volumes:
    # Option 1: Standard Docker volumes (data persists)
    mongo_data:
        driver: local
    mongo_config:
        driver: local

    # Option 2: If you really want bind mounts, remove the driver_opts